version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=bank
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - app-network

  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - HOST=localhost
      - APP_URL=https://coincorpback.onrender.com
      - NODE_ENV=development
      - DB_NAME=bank
      - DB_USER=admin
      - DB_PASSWORD_FILE=sircumsalot12343
      - DB_HOST=database-1.cjo2iiegkzn2.eu-central-1.rds.amazonaws.com
      - DB_PORT=3306
    env_file:
      - api.env
    secrets:
      - db-password
    networks:
      - app-network

volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
networks:
  app-network:
    driver: bridge
